const SUPABASE_URL='https://alucbkzjbsgvlqodvdjt.supabase.co';
const SUPABASE_KEY='sb_publishable_07DRB0pJl82rAW62fwZPxA_GgFRrBST';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let editingId=null;
const $=id=>document.getElementById(id);
function notice(text,error=false){$('msg').textContent=text;$('msg').classList.remove('hidden');$('msg').style.background=error?'#fff0f0':'#eef5ff';}
function loginNotice(text){$('loginMsg').textContent=text;$('loginMsg').classList.remove('hidden');}
async function ensureAdmin(){const {data:{user}}=await sb.auth.getUser(); if(!user)return false; const {data,error}=await sb.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle(); if(error||!data)return false; return true;}
async function boot(){const ok=await ensureAdmin(); if(ok){$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');await loadProducts();await loadVideos();}else{const {data:{user}}=await sb.auth.getUser();if(user) loginNotice('Este usuario no está autorizado como administrador.');}}
$('login').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){loginNotice(error.message);return}boot()};
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('#productsTab,#videosTab').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden')});
$('newProduct').onclick=()=>openEditor();$('closeEditor').onclick=()=>{$('productEditor').classList.add('hidden')};
function openEditor(p=null,vars=[]){editingId=p?.id||null;$('editorTitle').textContent=p?'Editar producto':'Nuevo producto';$('pName').value=p?.name||'';$('pCategory').value=p?.category||'jean';$('pDesc').value=p?.description||'';$('pSizes').value=(p?.sizes||[]).join(', ');$('pOrder').value=p?.sort_order||0;$('pActive').checked=p?.active!==false;$('deleteProduct').classList.toggle('hidden',!p);$('variants').innerHTML='';(vars.length?vars:[{}]).forEach(addVariantRow);$('productEditor').classList.remove('hidden');window.scrollTo({top:$('productEditor').offsetTop-80,behavior:'smooth'});}
function addVariantRow(v={}){const d=document.createElement('div');d.className='variant';d.innerHTML=`<div class="variant-head"><strong>Tono</strong><button type="button" class="btn danger remove">Quitar</button></div><div class="grid"><div><div class="field"><label>Nombre del tono</label><input class="tone" value="${esc(v.tone_name||'')}"></div><div class="field"><label>Precio (COP)</label><input class="price" type="number" min="0" step="100" value="${v.price??''}"></div><div class="field"><label>Stock</label><input class="stock" type="number" min="0" value="${v.stock??0}"></div></div><div><div class="field"><label>Foto</label><input class="image" type="file" accept="image/jpeg,image/png,image/webp"></div>${v.image_url?`<img class="thumb preview" src="${esc(v.image_url)}">`:'<div class="muted preview">Sin foto</div>'}<label class="check"><input class="active" type="checkbox" ${v.active!==false?'checked':''}> Variante visible</label></div></div>`;d.dataset.id=v.id||'';d.dataset.oldurl=v.image_url||'';d.querySelector('.remove').onclick=()=>d.remove();$('variants').appendChild(d);}
$('addVariant').onclick=()=>addVariantRow();
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function upload(file,bucket,folder){if(!file)return null;const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl;}
$('saveProduct').onclick=async()=>{try{if(!(await ensureAdmin()))throw new Error('Sesión de administrador no válida.');const sizes=$('pSizes').value.split(',').map(x=>x.trim()).filter(Boolean);const payload={name:$('pName').value.trim(),category:$('pCategory').value,description:$('pDesc').value.trim(),sizes,sort_order:Number($('pOrder').value||0),active:$('pActive').checked};if(!payload.name)throw new Error('Escribe el nombre del producto.');let product;if(editingId){const r=await sb.from('products').update(payload).eq('id',editingId).select().single();if(r.error)throw r.error;product=r.data;}else{const r=await sb.from('products').insert(payload).select().single();if(r.error)throw r.error;product=r.data;}
const rows=[...document.querySelectorAll('.variant')];for(const row of rows){const file=row.querySelector('.image').files[0];let imageUrl=row.dataset.oldurl||null;if(file) imageUrl=await upload(file,'product-images',product.id);const v={product_id:product.id,tone_name:row.querySelector('.tone').value.trim(),image_url:imageUrl,price:row.querySelector('.price').value===''?null:Number(row.querySelector('.price').value),stock:Number(row.querySelector('.stock').value||0),active:row.querySelector('.active').checked};if(!v.tone_name)continue;const id=row.dataset.id;if(id){const r=await sb.from('product_variants').update(v).eq('id',id);if(r.error)throw r.error;}else{const r=await sb.from('product_variants').insert(v);if(r.error)throw r.error;}}
notice('Producto guardado correctamente.');$('productEditor').classList.add('hidden');await loadProducts();}catch(e){notice(e.message||String(e),true)}};
$('deleteProduct').onclick=async()=>{if(!editingId||!confirm('¿Eliminar este producto y sus variantes?'))return;const {error}=await sb.from('products').delete().eq('id',editingId);if(error){notice(error.message,true);return}notice('Producto eliminado.');$('productEditor').classList.add('hidden');loadProducts()};
async function loadProducts(){const {data,error}=await sb.from('products').select('*').order('sort_order').order('created_at');if(error){notice(error.message,true);return}const ids=data.map(x=>x.id);let vars=[];if(ids.length){const r=await sb.from('product_variants').select('*').in('product_id',ids);if(r.error){notice(r.error.message,true);return}vars=r.data||[];}const by={};vars.forEach(v=>(by[v.product_id]??=[]).push(v));$('productList').innerHTML=data.map(p=>`<article class="product"><div class="row"><span class="pill">${esc(p.category)}</span>${p.active?'<span class="pill">VISIBLE</span>':'<span class="pill">OCULTO</span>'}</div><h3>${esc(p.name)}</h3><small>${(p.sizes||[]).join(' · ')||'Sin tallas'}</small><div>${(by[p.id]||[]).map(v=>`<span class="pill">${esc(v.tone_name)}${v.price!=null?' · $'+Number(v.price).toLocaleString('es-CO'):''}</span>`).join('')}</div><button class="btn ghost edit" style="margin-top:10px">Editar</button></article>`).join('')||'<p class="muted">No hay productos.</p>';[...document.querySelectorAll('.edit')].forEach((b,i)=>b.onclick=()=>openEditor(data[i],by[data[i].id]||[]));}
$('uploadVideo').onclick=async()=>{try{if(!(await ensureAdmin()))throw new Error('Sesión de administrador no válida.');const file=$('vFile').files[0];if(!file)throw new Error('Selecciona un video.');const title=$('vTitle').value.trim()||file.name;const url=await upload(file,'videos','uploads');const r=await sb.from('videos').insert({title,video_url:url,published:$('vPublished').checked}).select().single();if(r.error)throw r.error;notice('Video subido y registrado correctamente.');$('vTitle').value='';$('vFile').value='';await loadVideos();}catch(e){notice(e.message||String(e),true)}};
async function loadVideos(){const {data,error}=await sb.from('videos').select('*').order('created_at',{ascending:false});if(error){notice(error.message,true);return}$('videoList').innerHTML=(data||[]).map(v=>`<article class="video"><video controls preload="metadata" src="${esc(v.video_url)}"></video><strong>${esc(v.title)}</strong><p class="muted">${v.published?'Publicado':'Oculto'}</p><div class="row"><button class="btn ghost toggle" data-id="${v.id}" data-pub="${v.published}">${v.published?'Ocultar':'Publicar'}</button><button class="btn danger delvideo" data-id="${v.id}">Eliminar</button></div></article>`).join('')||'<p class="muted">Todavía no hay videos.</p>';document.querySelectorAll('.toggle').forEach(b=>b.onclick=async()=>{await sb.from('videos').update({published:b.dataset.pub!=='true'}).eq('id',b.dataset.id);loadVideos()});document.querySelectorAll('.delvideo').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar este video?')){await sb.from('videos').delete().eq('id',b.dataset.id);loadVideos()}})}
sb.auth.onAuthStateChange((_event)=>setTimeout(boot,0));boot();
