const SUPABASE_URL='https://alucbkzjbsgvlqodvdjt.supabase.co';
const SUPABASE_KEY='sb_publishable_07DRB0pJl82rAW62fwZPxA_GgFRrBST';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);

// Respaldo local: la tienda sigue funcionando aunque Supabase esté temporalmente fuera de servicio.
const fallbackProducts=[
{id:'cross',category:'jean',categoryLabel:'JEAN URBANO KIDS · TELA CROSS',name:'Jean Urbano Kids — Tela Cross',desc:'Diseño clásico y urbano. Tela Cross (98% algodón + 2% elastano).',sizes:['2','4','6','8','10','12','14','16'],tones:[{name:'Azul',img:'assets/cross_azul.jpeg'},{name:'Frost',img:'assets/cross_frost.jpeg'},{name:'Frost Medio',img:'assets/cross_frost_medio.jpeg'}]},
{id:'jogger',category:'jogger',categoryLabel:'JOGGER CLÁSICO',name:'Pantalón Jogger Clásico',desc:'Jogger infantil de estilo urbano.',sizes:['2','4','6','8','10','12','14','16'],tones:[{name:'Claro',img:'assets/jogger_claro.jpeg'},{name:'Gris',img:'assets/jogger_gris.jpeg'},{name:'Medio',img:'assets/jogger_medio.jpeg'},{name:'Negro',img:'assets/jogger_negro.jpeg'}]},
{id:'ancho',category:'baggi',categoryLabel:'ANCHO BAGGI',name:'Ancho Baggi',desc:'Silueta baggi de inspiración urbana.',sizes:['8','10','12','14','16','18'],tones:[{name:'Frost',img:'assets/ancho_frost.jpeg'},{name:'Medio',img:'assets/ancho_medio.jpeg'},{name:'Gris',img:'assets/ancho_gris.jpeg'}]},
{id:'bermuda',category:'bermuda',categoryLabel:'BERMUDA OVERSIZE',name:'Bermuda Oversize',desc:'Bermuda oversize de niño en tela rígida.',sizes:['8','10','12','14','16','18'],tones:[{name:'Azul Frost',img:'assets/bermuda_azul_frost.jpeg'},{name:'Azul Medio',img:'assets/bermuda_azul_medio.jpeg'},{name:'Gris Frost',img:'assets/bermuda_gris_frost.jpeg'}]},
{id:'baggi',category:'baggi',categoryLabel:'BAGGI CLÁSICO',name:'Baggi Clásico',desc:'Jean baggi de corte urbano.',sizes:['6','8','10','12','14','16','18'],tones:[{name:'Azul',img:'assets/baggi_azul.jpeg'},{name:'Claro',img:'assets/baggi_claro.jpeg'},{name:'Medio',img:'assets/baggi_medio.jpeg'},{name:'Negro',img:'assets/baggi_negro.jpeg'}]},
{id:'flecos',category:'baggi',categoryLabel:'BAGGI CON FLECOS',name:'Baggi con Flecos',desc:'Referencia con detalle distintivo de flecos/desflecado.',sizes:['12','14','16','18'],tones:[{name:'Frost',img:'assets/flecos_frost.jpeg'},{name:'Medio',img:'assets/flecos_medio.jpeg'},{name:'Gris',img:'assets/flecos_gris.jpeg'}]}
];
let products=[...fallbackProducts];
const grid=document.getElementById('productGrid'),filters=document.getElementById('filters'),modal=document.getElementById('productModal'),modalImage=document.getElementById('modalImage'),modalCategory=document.getElementById('modalCategory'),modalName=document.getElementById('modalName'),modalDesc=document.getElementById('modalDesc'),toneSelect=document.getElementById('toneSelect'),sizeOptions=document.getElementById('sizeOptions'),buyBtn=document.getElementById('buyBtn');
let currentProduct=null,currentTone=null,currentSize=null;
const categoryLabel={jean:'JEANS',jogger:'JOGGERS',baggi:'BAGGI',bermuda:'BERMUDAS'};
function renderProducts(filter='all'){
 const list=filter==='all'?products:products.filter(p=>p.category===filter);
 grid.innerHTML=list.map(p=>{const t=p.tones?.[0];return `<article class="product-card"><div class="product-img">${t?.img?`<img src="${esc(t.img)}" alt="${esc(p.name)}" loading="lazy">`:'<div class="video-empty">Sin foto</div>'}</div><div class="product-body"><div class="product-tag">${esc(p.categoryLabel||categoryLabel[p.category]||'AVILESTILO')}</div><h3>${esc(p.name)}</h3><p>${esc(p.desc||'')}</p><div class="swatches">${(p.tones||[]).map(x=>`<span class="swatch">${esc(x.name)}</span>`).join('')}</div><div class="card-sizes">Tallas: ${(p.sizes||[]).join(' · ')}</div><button class="btn card-btn" data-id="${esc(p.id)}">Ver tonos y tallas</button></div></article>`}).join('')||'<p>No hay productos publicados.</p>';
 grid.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.id)));
}
function openProduct(id){currentProduct=products.find(p=>p.id===id);if(!currentProduct)return;currentTone=currentProduct.tones[0];currentSize=null;modalCategory.textContent=currentProduct.categoryLabel||categoryLabel[currentProduct.category]||'AVILESTILO®';modalName.textContent=currentProduct.name;modalDesc.textContent=currentProduct.desc||'';toneSelect.innerHTML=(currentProduct.tones||[]).map((t,i)=>`<option value="${i}">${esc(t.name)}</option>`).join('');sizeOptions.innerHTML=(currentProduct.sizes||[]).map(s=>`<button class="size-option" data-size="${esc(s)}">${esc(s)}</button>`).join('');modalImage.src=currentTone?.img||'';modalImage.alt=currentProduct.name+' '+currentTone?.name;modal.classList.add('open');modal.setAttribute('aria-hidden','false');sizeOptions.querySelectorAll('.size-option').forEach(btn=>btn.addEventListener('click',()=>{currentSize=btn.dataset.size;sizeOptions.querySelectorAll('.size-option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')}));}
toneSelect.addEventListener('change',e=>{if(!currentProduct)return;currentTone=currentProduct.tones[Number(e.target.value)];modalImage.src=currentTone.img;modalImage.alt=currentProduct.name+' '+currentTone.name});
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.getElementById('modalClose').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
buyBtn.addEventListener('click',()=>{if(!currentProduct)return;if(!currentSize){alert('Selecciona una talla primero.');return}const msg=`Hola AVILESTILO 👋\n\nQuiero comprar:\nProducto: ${currentProduct.name}\nTono: ${currentTone.name}\nTalla: ${currentSize}\n\n¿Me confirman disponibilidad y precio?`;window.open(`https://wa.me/573003958114?text=${encodeURIComponent(msg)}`,'_blank')});
filters.addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;filters.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)});
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function loadProductsFromSupabase(){if(!sb)return;try{const {data,error}=await sb.from('products').select('*').eq('active',true).order('sort_order').order('created_at');if(error||!data?.length)return;const ids=data.map(p=>p.id);const r=await sb.from('product_variants').select('*').in('product_id',ids).eq('active',true);if(r.error)return;const by={};(r.data||[]).forEach(v=>(by[v.product_id]??=[]).push(v));products=data.map(p=>({id:p.id,category:p.category,categoryLabel:(categoryLabel[p.category]||p.category).toUpperCase(),name:p.name,desc:p.description,sizes:p.sizes||[],tones:(by[p.id]||[]).map(v=>({name:v.tone_name,img:v.image_url,price:v.price,stock:v.stock}))})).filter(p=>p.tones.length);renderProducts();}catch(e){console.warn('Supabase no disponible; usando catálogo local.',e)}}
async function loadVideos(){const box=document.getElementById('publicVideos');if(!box||!sb)return;try{const {data,error}=await sb.from('videos').select('*').eq('published',true).order('created_at',{ascending:false});if(error||!data?.length)return;box.innerHTML=data.map(v=>`<article class="public-video"><video controls playsinline preload="metadata" src="${esc(v.video_url)}"></video><div class="public-video-body"><h3>${esc(v.title)}</h3></div></article>`).join('')}catch(e){console.warn('No se pudieron cargar videos',e)}}
renderProducts();loadProductsFromSupabase();loadVideos();

const menuToggle=document.querySelector('.menu-toggle'),nav=document.getElementById('mainNav');menuToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const chatFab=document.getElementById('chatFab'),chat=document.getElementById('chat'),chatClose=document.getElementById('chatClose');chatFab.addEventListener('click',()=>{chat.classList.add('open');chat.setAttribute('aria-hidden','false');document.getElementById('chatInput').focus()});chatClose.addEventListener('click',()=>{chat.classList.remove('open');chat.setAttribute('aria-hidden','true')});document.getElementById('chatForm').addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('chatInput'),text=input.value.trim();if(!text)return;const body=document.getElementById('chatBody');body.insertAdjacentHTML('beforeend',`<div class="user-msg">${esc(text)}</div>`);input.value='';setTimeout(()=>body.insertAdjacentHTML('beforeend','<div class="bot-msg">¡Claro! Puedes elegir una referencia, tono y talla en la colección. Si prefieres, escríbenos directamente por WhatsApp al 300 395 8114.</div>'),350);body.scrollTop=body.scrollHeight});
